title: pecha.jobs
logo: /assets/img/pechajobs.png
description: We provide data sourcing and processing services for individuals and organizations who are working to preserve and promote the Tibetan language, culture, and religion. Our core services include labeling, data preparation, proofreading, input, linking, and transcription.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
