title: pecha.jobs
logo: /assets/img/pecha jobs logo.png
description: Providing technical services to support the preservation and promotion of the Tibetan language, culture, and religion.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
